//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 10:46:47 AM MSK 
//


package ru.datana.steel.mes.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompositionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CompositionTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="STEEL"/&gt;
 *     &lt;enumeration value="CAST_IRON"/&gt;
 *     &lt;enumeration value="SLAG"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CompositionTypeType")
@XmlEnum
public enum CompositionTypeType {


    /**
     * Сталь
     * 
     */
    STEEL,

    /**
     * Чугун
     * 
     */
    CAST_IRON,

    /**
     * Шлак
     * 
     */
    SLAG;

    public String value() {
        return name();
    }

    public static CompositionTypeType fromValue(String v) {
        return valueOf(v);
    }

}
