//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 10:46:47 AM MSK 
//


package ru.datana.steel.mes.xml.pojo;

import lombok.Data;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * Наименование химического элемента или параметра и результат
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlledElementItemType", propOrder = {
    "controlledElementName",
    "controlledElementValue"
})
@Data
public class ControlledElementItemType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ControlledElementNameType controlledElementName;
    @XmlElement(required = true)
    protected BigDecimal controlledElementValue;

}
